title: Adewale Adeleke Data Analytics Portfolio
logo: Image.jpg
description: A certified and highly skilled data analyst, with proficiency in Microsoft Excel, SQL, PowerBi, Python etc.
#show_downloads: true
#google_analytics:
theme: jekyll-theme-minimal
